insert into T_ADDRESS(ADDRESS_ID,ADDRESS_PINCODE,ADDRESS_STATE,ADDRESS_TOWN) values(1001,'560100','AP','KADAPA');

insert into T_EMPLOYEE(EMP_ID,EMP_EMAIL,EMP_NAME,ADDRESS_ID) values (2001,'guru.svu31@gmail.com','Gurunath',1001);

insert into T_PROJECT (PROJECT_ID, PROJECT_NAME,EMP_ID) values (3001,'EMS',2001);
insert into T_PROJECT (PROJECT_ID, PROJECT_NAME,EMP_ID) values (3002,'SMS',2001);